---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin-pw
  labels:
    app: {{ template "conjur-oss.name" . }}
    chart: {{ template "conjur-admin-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: service
{{- with .Values.conjurLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  key: {{ .Values.adminPW | b64enc }}
